# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Users/\u041a\u0438\u0440\u044f/.jdks/jbr-21.0.11

android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Оптимизация
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Kotlin
kotlin.incremental=true

# Android
android.enableJetifier=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
